#!/usr/bin/env python3
"""Embed JSON assets into js/demo-data.js for file:// offline opening."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "js" / "demo-data.js"


def main() -> None:
    task = json.loads((ROOT / "assets/meta/task.json").read_text(encoding="utf-8"))
    manifest = json.loads((ROOT / "assets/meta/manifest.json").read_text(encoding="utf-8"))
    trajectory = json.loads((ROOT / "assets/trajectory.json").read_text(encoding="utf-8"))
    payload = {"task": task, "manifest": manifest, "trajectory": trajectory}
    OUT.write_text(
        "// Auto-generated by tools/embed_demo_data.py — do not edit by hand.\n"
        f"window.DEMO_DATA = {json.dumps(payload, ensure_ascii=False)};\n",
        encoding="utf-8",
    )
    print("WROTE", OUT, f"({OUT.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
